name: organizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  fl_chart: ^0.70.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.5.0
  http: ^1.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/organizer_logo_a.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/

